services:
  test-backend-6:
    build:
      context: .
      target: production
    image: test-backend-6
    container_name: test-backend-6
    depends_on:
      - test-backend-6-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-backend-6-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  test-backend-6-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: test-backend-6
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
