# For documentation on how to use, please go here: https://github.com/DEFRA/adp-aso-helm-library?tab=readme-ov-file#adp-platform-azure-service-operator-helm-library-chart.
# You may create Queues, Topics, Subscriptions, Storage Accounts, Databases and Role Assignments on these here.

namespaceTopics:
  - name: test-backend-5
    owner: 'no'
    roleAssignments:
      - roleName: 'TopicReceiver'
postgres:
  db:
    name: test-backend-6 
    charset: UTF8
    collation: en_US.utf8